### ISSUE TITLE
React component sample

### ISSUE THREAD

**Issue by whitetigle** [fable-compiler/fable2-samples#10]
I think it would be great to add a React component sample. We might ask @ericharding, who released an awesome [React component with fable](https://github.com/ericharding/SouthernFriedReact)?

**Comment by ericharding** [comment]
That's a great idea. I'll see about putting together a PR soon.

**Comment by ericharding** [comment]
Added PR #15 
Side note: I think it would be really neat to demo this on jsfiddle or codepen or something which should be possible with something like [unpkg.io](https://unpkg.io/fs-react-component@0.0.2/build/index.js).  However, I'm utterly defeated by the JS module system. 🤷‍♂

**Comment by alfonsogarciacaro** [comment]
Thanks @ericharding! You mean publishing the component to npm as a sample? Yes, this should be possible, you can use `Fable.Core.JsInterop.exportDefault` to expose the component easily.

It's also possible to show how interaction works in Fable REPL by using the HTML tab to write JS: [example](https://fable.io/repl/#?code=LYewJgrgNgpgBAJRgQwMYBcDCJgAcQB2MB6AUKSLsXAGLIBGsAdNgE4wVUG0PNsxMAUgGcAkiRitKnanUYCkaMqQD0KuABEYqKMnZwAZhAIYAloThgYB00TBwA5lBD1kUKAE84tuOgAW8AASACoAsgAycAA8wqisprjoAHy+yA6ksOhwANpRAOLOrlBJALpwoMboAIK4uHAAFKg4AFyIKBgAorDAxOjBHlRRAOQAClK4wkkAlK3GplkAvHAAVsIAcsjopgBuHKrqNMZmhNh4hL1MAPIG3sLeEgRW9uggcPTwEMIw9gZSwLQAYn2cGCrxgAA98F9vFkfIIAMpwADu8CI3zgyDgwigpgcfnQnnK4FMNnR2z0pmQJGB9QA6vBhH4QNB7DiANYwQnIMD2ea+V7+eByZiKDBwHH0Vh6DxTUjoAZCo5bE44fBEEjI+Z+UhwXVY9CbUyocowYDvVi0ECsBE6vV2+16+rsR6SVqjcbCAC0SVF6C6pt6ABpbQ7Q7qAPxgUzCXC6DwbHqtYToeIEBzBsOZ8M9UCmABeMFpWrdY0od29cHdZbgFfoIBAUFlmdDrV9-p6JH6gyrExSCxD9uAm1QfhNuYLRf8mv8A7tAB84PCcPA9DAOgBHCBuGtJWehzJjkDt3pwJa+gBCtijaeETF9TBzICdxCsrEDGPYG63jb3DqH6BHSxo1jZB42QHpp21ZtdQXJcIIIcD4ArR9jxISNgLjBN4CiT04AAIlCU0nzwuAAGo4AQiDyLwqY8N-e0FzWc4dwaJtoJQ7penoxjmIrYw63BOBnVfcg1DgDpHjgEAbjrUxYFYED0BgABCOBwhgdAhjuZM9CyKwbAIWwHCkiALSaM51WUMT4VsVB4EFOBcA9KT6GWbRYTuOIUCUn4-jgQRkHJWJ4kSGEtLeGBk35CLLGsYhhB2eB6k+eBKGVAhhCmQwrV8AJ+TqWBdigDF0BTUx6AgJTb2BUQbg8Zk4BS+xMWTVNjL5YBcXxZErTZN5KtyyR4GjCjXhHbQ+pecpkA5LFTPsvLUDceTHKkbZTCeDE4HJKAIAEOUFTgUsJlPOABwYVqlDHc0KMQuAkzKtMpMScwCFE9RargeqIDgCEqDFBzzLVE8pveOAmgyiAel8nAVkC5BgoSLIkS1fz4QADS+hqlu4P6QGhTFXH0IwTHSjE7kxdgrqB84NSpZ4-E2TV3B61g+vqWzduvYymRANlMqYGq6ux5bcpG35YZoAEYR6lkMTFBGtpAnwSeObhhFeb7ZagexGd2aKkSlOo+RRqdDlJ17TmBkgrhueocoAA2k821YdrKSSxn60V1+t+YN3qmDOsSvhgVp8XQCZmjUAxeAEcwVEYEAHBUKoCAIZkTCMz1hRgT1fU9ABWJh8WAKAMg02hjCt2msnqJyy2aY7MtPAcD0o+Aln05BoGqVhjPriYmHb-D07rMAPDou0o22HIymyVqGhjVN0BuPDAk5Zw4AAUmEEj26mEp3rgABVBKnpd9Lq8spgaCtBFkXgHGMR5Z+o3S7d3j18xTPFUxZsffMhoLA5UxKgT4Lx-hRhjHGW6PRy5ZBzgXc2V8Tz9jtBfS2qoa43zvvCKITddxhnqMgrBlkMxhgAROVGSwYCbjcMIc8lUMGEGEOQ0MUCQJgQgksPCOcUEkBokfeEL5Brg1ISDV498DA5QqCQIyMJSCyOqLUHg8gkFV3EdSIAA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwssOYLona6pMJl3aJTAEQB9TwAkA8gDKAt5KUHQARrpK2qgSYAB0pNocaDRxdNzxEHRc8QBWuu4wwEq29o5W2DZ2Dk4ubl6+gcGeoRFRMShx5GgcEInJqemZ2bkFRSVltZW4UxVwSkqYAKpcxhzaYDRcKLxQQpgA7kiSKFxcHE40+pgAUgEAGs5CPCjyxEgxC0sA6ieHHBoUDQmC4SCQIKISSQSQ4EiQul0G0w620mDAWjAcGM22GXEwEEBPAAgqRSAAKABiKHCUCQnAgpG4fDAAEpMABvOA4TAAJViYAAIn4ALLxGJcNCfcncnk4Ra4am0+l9JlgniglD4DxKukAQncmCUMx5-K6CTsqF4AFE6fgeFSaXSGWqWQAaTma-AALkw7l1SANmAAvqy3bK5ZhehIaPaEgBzAi2pBxgBCQgAkmhye4UGT3KzWXBgxHcKUavMSiBUBgEMBwikDhIoChER48xQpK8cp8iqXgGhGJg6Gh2-nJC227n88UlIOGPASg20EJ4IgVJBYHAgA&css=BYFwtgNgNAUARgewCYE8AEBvGadoGYIB2IAtAM4CWAXgKYBcaAjAGwAOAHgNwwC+MMAOjABDCoRIBjIiFGEaAJ0zZcSCmVYRhKBngg0uynAHcKSEMAaMADFYCk3XGmA0KAc1CWb9w2gBWAVzIQCjwUSWkaYgYJSJAFB1xhCDdxCjiwMmjY+J9dfRJVeRoJYKJohAh-MEJuPkExVn8QJUdWYSRVQlcGAQAmAFYisAScAmJyanomNgNHEzMLNAGrDhG0EXlXMRJEEBAEMEsh2pggA).

> Unfortunately, `FunctionComponent.Of` is intended to produce code more easily callable from F#. I've written a `ForJS` variant that works when sending the component to JS.

**Comment by ericharding** [comment]
This actually works just fine as long as webpack is involved.  The sample produces just produces an AMD module which I can't figure out how to load in the various online JS editors.  It isn't a problem with getting the function exported so much as "require" is not defined type thing.

**Comment by alfonsogarciacaro** [comment]
Not sure if it works with the online editors, but you can also set the (output.library)[https://webpack.js.org/configuration/output/#outputlibrary] option in Webpack to put the contents of your library in a global variable. So if you have:

```js
module.exports = {
  //...
  output: {
    library: 'FableComponents'
  }
};
``` 

You can use them like:

```js
    <FableComponents.StandardComponent name="standard" />
    <FableComponents.FunComponent name="bare" />
    <FableComponents.Fable5FunComponent name="Memo Component" />
```

**Comment by ericharding** [comment]
That might just work for the online version.  Thanks, I'll give it a try.

I think it's probably best to keep the sample how it is, though, because it will be more idiomatic to consume from JS.
