### ISSUE TITLE
Build error in minimal sample, not sure how to troubleshoot

### ISSUE THREAD

**Issue by aggieben** [fable-compiler/fable2-samples#24]
I have an up-to-date clone of the repo, and ran `yarn install` and `yarn start` as suggested in the getting started docs, and webpack failed with a build error:

![image](https://user-images.githubusercontent.com/1321/73596880-1eec6180-44ec-11ea-9ed2-aba56f9667f6.png)

The error above occurred after I added a build command that just calls executes webpack with no arguments, but it's identical to what's produced when running webpack-dev-server.

I'm new to Fable, and not super experienced with webpack and I'm not sure how to troubleshoot this.  My first thought was to run the msbuild commands independently.  This is the result:

![image](https://user-images.githubusercontent.com/1321/73596903-6ffc5580-44ec-11ea-9444-58e564e94fb0.png)

I'm not sure what to do with this.  Is Fable.Elmish supposed to have a .paket directory?  
I'd love to get up and running and building in Fable, but I'm a bit stuck.

**Comment by MangelMaxime** [comment]
Hello @aggieben ,

I cannot reproduce your problem. Also, the readme instructions say to use `npm install` and `npm start` and if I use this command it's working for me.

Note that using `yarn` doesn't change a lot of thing, but you will have a new dependencies list computed and not the one stored inside of `package-lock.json`.

Can you please try with  `npm install` and `npm start`? 

Just in case it helps, I tested the project with `dotnet 3.1.101` (you can check your installed version with `dotnet --version`)
