### ISSUE TITLE
App.fs and package.json updates

### ISSUE THREAD

**Issue by brettrowberry** [fable-compiler/fable2-samples#3]
Alfonso, this is the best Hello World! Thanks! 
In the App.fs I noticed in the comment that Elmish was spelled 'Emish'.
When I built the app, it also suggested revving "@babel/core": "^7.1.2" to at least "@babel/core": "^7.1.6".

**Comment by alfonsogarciacaro** [comment]
Good point, thank you! Would you mind sending a PR with the changes? That would be really helpful :)

**Comment by whitetigle** [comment]
It seemed to be ok. So I'll close this one.
