### ISSUE TITLE
Node sample please

### ISSUE THREAD

**Issue by Zaid-Ajaj** [fable-compiler/fable2-samples#4]
The minimal sample for the browser is amazingly simple! Can we have a node sample too with fable-splitter please?

**Comment by alfonsogarciacaro** [comment]
Before that we'll probably should split the Fable.Node packages as we're doing with Fable.Browser :)

For an easy example with splitter you can check https://github.com/fable-compiler/static-web-generator

**Comment by whitetigle** [comment]
[node sample with fable-splitter ready to use.](https://github.com/fable-compiler/fable2-samples/tree/master/nodejs)
